### ISSUE TITLE
unable to make bootstrap-datepicker orient to bottom

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/custom-widgets#241]
var json = {
    "elements": [
        {
            "name": "date",
            "type": "bootstrapdatepicker",
            "inputType": "date",
            "title": "Your favorite date:",
            "dateFormat": "mm/dd/yy",
            "isRequired": true,
            "orientation":"bottom"
        }
    ]
};

![image](https://user-images.githubusercontent.com/45259204/102966198-39b73280-4511-11eb-8786-2f8af2940d61.png)

**Comment by tsv2013** [comment]
There is no such an option at this moment. You can create a pull request.
Here is the place where options are set - https://github.com/surveyjs/custom-widgets/blob/master/src/bootstrapdatepicker.js#L94-L103

**Comment by anaskhanstack** [comment]
Can we setup the orientation-bottom using jquery?if yes the where (e.g. survey.onValueChange)?

**Comment by tsv2013** [comment]
To set up the orientation option (https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#orientation) you need to pass it from a survey question to bootstrap-datepicker constructor (here - https://github.com/surveyjs/custom-widgets/blob/master/src/bootstrapdatepicker.js#L94-L103). There is no such an option at this moment. You can add it in your code.

To be honest the default orientation option ("auto") is the best value because in case of using other values you will need to calculate whether the space below is enough to show dropdown.
